# Generated by Django 6.0.1 on 2026-01-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Name ")),
                (
                    "product_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Product Code"
                    ),
                ),
                ("price", models.CharField(max_length=50, verbose_name="Price")),
                (
                    "sale_price",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="sale price "
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Color"
                    ),
                ),
                (
                    "memory",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Memory"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Manufacturer",
                    ),
                ),
                (
                    "display_size",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Size display",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Resolution"
                    ),
                ),
                (
                    "reviews_count",
                    models.IntegerField(default=0, verbose_name="Count reviews"),
                ),
                ("images", models.JSONField(default=list, verbose_name="Photo link")),
                (
                    "specs",
                    models.JSONField(default=dict, verbose_name="characteristic"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
